export const campaignTypes = { one_shot: 'One-shot', mini_campaign: 'Mini campaign', long_campaign: 'Long campaign', open_table: 'Open table' };
export const startingPoints = { session_zero: 'Session zero first', tavern_start: 'Classic tavern start', mid_action: 'Start mid-action', custom_world: 'Homebrew world intro', published_adventure: 'Published adventure' };
export const worldToneOptions = { custom: 'Custom Setting', high_fantasy: 'High Fantasy', classic_fantasy: 'Classic Sword & Sorcery', epic_fantasy: 'Epic Fantasy', gothic_horror: 'Gothic Horror', magipunk_noir: 'Magipunk / Noir', planar_adventure: 'Planar Adventure', fantasy_space: 'Fantasy Space' };
export const sessionZeroOptions = [
  { id: 'safety', label: 'Safety tools and table boundaries' }, { id: 'tone', label: 'Tone, themes, and campaign style' }, { id: 'party_roles', label: 'Party roles and character links' }, { id: 'house_rules', label: 'House rules and rules edition' }, { id: 'schedule', label: 'Schedule, attendance, and session length' }, { id: 'rewards', label: 'Loot, levelling, and rewards' },
];
export const initialCampaignForm = { name: '', world_name: '', description: '', rules_edition: '2024', campaign_type: 'long_campaign', starting_point: 'session_zero', world_setting: 'custom', session_zero: ['safety', 'tone', 'party_roles', 'house_rules'] };
export function safeArray(value) { return Array.isArray(value) ? value.filter(item => item && typeof item === 'object') : []; }
export function recordId(record) { return record?.id || record?._id || record?.campaign_id || record?.campaignId || record?.character_id || record?.characterId || ''; }
export function characterTitle(character) { return character?.name || character?.character_name || 'Unnamed Character'; }
export function characterMeta(character) { const level = character?.level || 1; const className = character?.character_class || character?.class_name || character?.class || 'Adventurer'; return `Level ${level} ${className}`; }
export function campaignTitle(campaign) { return campaign?.name || campaign?.campaign_name || 'Untitled Campaign'; }
export function campaignMeta(campaign) { return `${campaign?.player_count || 0} players · ${campaign?.system || campaign?.setting || 'Fantasy'}`; }
export function buildWorldSettingNotes(form) { const checkedItems = sessionZeroOptions.filter(item => form.session_zero.includes(item.id)).map(item => item.label); const setupLines = [`Campaign type: ${campaignTypes[form.campaign_type] || form.campaign_type}`, `Starting point: ${startingPoints[form.starting_point] || form.starting_point}`, `World tone: ${worldToneOptions[form.world_setting] || form.world_setting}`]; if (checkedItems.length) setupLines.push(`Session zero checklist: ${checkedItems.join('; ')}`); if (form.description.trim()) setupLines.push(`GM notes: ${form.description.trim()}`); return setupLines.join('\n'); }
export function statusMessage(status, checkedAt) { if (status === 'Ready') return `Backend is responding normally${checkedAt ? ` · checked ${checkedAt}` : ''}.`; if (status === 'Slow') return `Backend responded, but slowly${checkedAt ? ` · checked ${checkedAt}` : ''}. This can happen when a free host wakes up.`; if (status === 'Offline') return `Backend health check failed${checkedAt ? ` · checked ${checkedAt}` : ''}. Try refresh, then check the host if it continues.`; return 'Checking backend health...'; }
