import { theme } from './dashboardConfig';

export const pageStyle = { minHeight: '100dvh', background: theme.bg, color: theme.text, padding: 'clamp(12px, 3vw, 26px)', overflowX: 'hidden', overflowY: 'auto' };
export const headerStyle = { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 14, flexWrap: 'wrap', background: theme.panel, border: `1px solid ${theme.border}`, borderRadius: 8, padding: 14, marginBottom: 16 };
export const eyebrowStyle = { color: theme.accentHover, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1.2, fontWeight: 900, margin: '0 0 4px' };
export const titleStyle = { color: theme.text, fontSize: 'clamp(24px, 4vw, 34px)', fontWeight: 900, margin: 0 };
export const subtitleStyle = { color: theme.textSecondary, fontSize: 13, lineHeight: 1.5, margin: '4px 0 0' };
export const headerActionsStyle = { display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center', maxWidth: '100%' };
export const headerButtonStyle = (disabled) => ({ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 7, minHeight: 42, background: disabled ? theme.panelSoft : theme.accentSoft, border: `1px solid ${theme.border}`, borderRadius: 8, color: disabled ? theme.muted : theme.textSecondary, padding: '0 11px', fontWeight: 800, cursor: disabled ? 'not-allowed' : 'pointer' });
export const quickGridStyle = { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(min(250px, 100%), 1fr))', gap: 12, marginBottom: 16 };
export const actionCardStyle = (primary, disabled) => ({ minHeight: 132, display: 'flex', alignItems: 'center', gap: 12, background: primary ? theme.elevated : theme.panel, border: `1px solid ${primary ? theme.borderStrong : theme.border}`, borderRadius: 10, color: theme.text, padding: 16, cursor: disabled ? 'not-allowed' : 'pointer', opacity: disabled ? 0.55 : 1, textAlign: 'left', maxWidth: '100%' });
export const actionIconStyle = (primary) => ({ width: 46, height: 46, flex: '0 0 auto', display: 'flex', alignItems: 'center', justifyContent: 'center', background: primary ? theme.accent : theme.accentSoft, color: '#FFFFFF', border: `1px solid ${theme.borderStrong}`, borderRadius: 8 });
export const actionTitleStyle = { color: theme.text, fontSize: 17, fontWeight: 900, marginBottom: 5 };
export const actionTextStyle = { color: theme.textSecondary, fontSize: 13, lineHeight: 1.45, marginBottom: 10 };
export const actionMetaStyle = (disabled) => ({ display: 'inline-flex', color: disabled ? theme.muted : theme.accentHover, fontSize: 11, fontWeight: 900, textTransform: 'uppercase', letterSpacing: 0.8 });
export const summaryGridStyle = { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(min(320px, 100%), 1fr))', gap: 12, marginBottom: 16 };
export const panelStyle = { background: theme.panel, border: `1px solid ${theme.border}`, borderRadius: 10, padding: 14 };
export const panelHeaderStyle = { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 10, marginBottom: 12, flexWrap: 'wrap' };
export const panelTitleStyle = { color: theme.text, fontSize: 18, fontWeight: 900, display: 'flex', alignItems: 'center', gap: 8, margin: 0 };
export const smallLinkButtonStyle = { background: 'transparent', border: `1px solid ${theme.border}`, borderRadius: 8, color: theme.accentHover, padding: '7px 10px', cursor: 'pointer', fontWeight: 800 };
export const listItemStyle = { width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 10, background: theme.panelSoft, border: `1px solid ${theme.border}`, borderRadius: 8, padding: 12, cursor: 'pointer', textAlign: 'left' };
export const emptyStyle = { background: theme.panelSoft, border: `1px dashed ${theme.border}`, borderRadius: 8, padding: 24, textAlign: 'center' };
export const noticeStyle = { display: 'flex', gap: 10, alignItems: 'flex-start', background: theme.panelSoft, border: `1px solid ${theme.border}`, borderRadius: 10, padding: 12, fontSize: 13, lineHeight: 1.5 };
export const mobileTabsStyle = { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8, marginBottom: 12, position: 'sticky', top: 0, zIndex: 5, background: theme.bg, paddingBottom: 8 };
export const mobileTabButtonStyle = (active) => ({ minHeight: 44, background: active ? theme.accent : theme.panel, color: active ? '#FFFFFF' : theme.textSecondary, border: `1px solid ${active ? theme.accentHover : theme.border}`, borderRadius: 8, fontWeight: 900, cursor: 'pointer' });
export const mobileSectionStyle = { display: 'grid', gridTemplateColumns: '1fr', gap: 12, marginBottom: 16 };
export const modalBackdropStyle = { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.72)', zIndex: 1000, display: 'grid', placeItems: 'center', padding: 14 };
export const modalStyle = { width: 'min(760px, 100%)', maxHeight: '92dvh', overflowY: 'auto', background: theme.panel, border: `1px solid ${theme.borderStrong}`, borderRadius: 12, padding: 18, display: 'flex', flexDirection: 'column', gap: 12 };
export const modalTitleStyle = { color: theme.text, fontSize: 22, fontWeight: 900, margin: 0 };
export const compactFormGridStyle = { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(min(220px, 100%), 1fr))', gap: 10 };
export const fieldLabelStyle = { color: theme.textSecondary, fontSize: 12, fontWeight: 900, display: 'flex', flexDirection: 'column', gap: 6, marginTop: 4 };
export const fieldStyle = { width: '100%', minHeight: 42, background: theme.panelSoft, color: theme.text, border: `1px solid ${theme.border}`, borderRadius: 8, padding: '9px 10px' };
export const toggleGridStyle = { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(min(220px, 100%), 1fr))', gap: 10 };
export const toggleCardStyle = { display: 'flex', gap: 10, alignItems: 'flex-start', background: theme.panelSoft, border: `1px solid ${theme.border}`, borderRadius: 8, padding: 10, color: theme.textSecondary, fontSize: 12 };
export const classGridStyle = { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))', gap: 8 };
export const classPillStyle = (active) => ({ display: 'flex', alignItems: 'center', gap: 8, background: active ? theme.accentSoft : theme.panelSoft, border: `1px solid ${active ? theme.borderStrong : theme.border}`, borderRadius: 8, padding: '8px 10px', color: theme.textSecondary, fontSize: 12, cursor: 'pointer' });
export const modalActionsStyle = { display: 'flex', justifyContent: 'flex-end', gap: 10, flexWrap: 'wrap', marginTop: 4 };
export const loadingPanelStyle = { display: 'grid', placeItems: 'center', gap: 10, background: theme.panel, border: `1px solid ${theme.border}`, borderRadius: 12, padding: 24, maxWidth: 520, textAlign: 'center' };
