export const RELEASE_NOTES = [
  {
    id: 'player-sheet-reward-sync-v1',
    date: 'Latest',
    audience: 'GMs and Players',
    title: 'Granted equipment now lands ready on player sheets',
    summary: 'When a GM grants an item as equipped or auto-attuned, the player sheet now recognises those flags, places ready gear into the correct equipped slot, recalculates armour class where needed, and shows attunement status clearly.',
    tags: ['Inventory', 'Rewards', 'Character Sheet'],
  },
  {
    id: 'gm-encounters-combat-control-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'GM Encounters now uses Combat Control',
    summary: 'The GM Encounters tab now uses the same Combat Control workflow as Live Play, including saved encounters, party merge, monsters, NPCs, story combat beats, loot drops, and launch readiness instead of the older split combat setup shell.',
    tags: ['Combat', 'Encounters', 'Live Play'],
  },
  {
    id: 'story-combat-beats-bridge-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'Story Combat Beats now feed Combat Control',
    summary: 'Combat Control now shows combat beats from the active Story Arc chapter. GMs can mark beats planned/ready/ran/skipped, create encounters from beats, link beats to saved encounters, and launch linked fights with the current party.',
    tags: ['Story Arcs', 'Combat', 'Encounters'],
  },
  {
    id: 'player-display-target-layouts-v1',
    date: 'Latest',
    audience: 'GMs and Players',
    title: 'Player Display now supports TV and virtual table layouts',
    summary: 'The Player Display Remote now lets GMs choose between a Standing TV layout for big cinematic reveals and a Virtual Table layout for map-first table or VTT-style use. Reveals, maps, NPCs, combat, and dice recaps adjust to the chosen screen type.',
    tags: ['Player Display', 'Live Play', 'Maps'],
  },
  {
    id: 'rook-shop-stock-builder-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'Rook Shop Stock Builder added',
    summary: 'Inventory & Rewards now includes a Rook shop helper. GMs can set a shop level, pricing style, and a few starter items, then let Rook fill the shelves with level-appropriate generic stock that can be added to party loot.',
    tags: ['Inventory', 'Shops', 'ROOK'],
  },
  {
    id: 'npc-gear-combat-grants-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'NPC gear can now affect combat stats',
    summary: 'Inventory reward handoff now supports NPC/enemy recipients. Equipping gear on an NPC can update their combat profile, including AC bonuses, weapon attacks, damage dice, damage type, and gear notes for encounter use.',
    tags: ['Inventory', 'NPCs', 'Combat'],
  },
  {
    id: 'combat-loot-grant-ready-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'Combat loot can now include gear details',
    summary: 'Combat Loot Drop now captures weapon, armour, shield, magic item, damage, attack bonus, AC bonus, equip slot, attunement, and GM notes so post-fight rewards are ready for Inventory handoff and character-sheet grants.',
    tags: ['Combat', 'Inventory', 'Rewards'],
  },
  {
    id: 'combat-loot-drop-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'Combat Loot Drop added',
    summary: 'Combat Control now has a quick loot drop panel so GMs can add post-fight rewards straight into party inventory, then grant them later with auto-attune and equipped-ready options.',
    tags: ['Combat', 'Inventory', 'Rewards'],
  },
  {
    id: 'combat-party-merge-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'Saved encounters can launch with the current party',
    summary: 'Combat now lets saved monster/NPC encounters launch with the current party automatically added. GMs can still start enemies-only when needed, but ordinary saved encounters no longer require rebuilding the player side every time.',
    tags: ['Combat', 'Encounters', 'Monsters'],
  },
  {
    id: 'homebrew-rook-builders-v1',
    date: 'Latest',
    audience: 'GMs and Creators',
    title: 'Homebrew Workshop now has Rook-assisted builders',
    summary: 'Homebrew Workshop now supports Monster / Creature, NPC Maker, and Custom Rule drafts. Fill in what you know, then ask Rook to complete missing stat blocks, NPC hooks, rule text, examples, and settings from the choices already made.',
    tags: ['Homebrew', 'ROOK', 'Monsters', 'NPCs', 'Custom Rules'],
  },
  {
    id: 'combat-ready-npcs-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'Quick NPCs now generate combat stat blocks',
    summary: 'The quick NPC generator now creates usable combat NPCs with ability scores, HP, AC, proficiency, skills, saving throws, attacks, abilities, spells where relevant, copyable stat blocks, and a save-to-campaign flow.',
    tags: ['NPCs', 'Combat', 'ROOK'],
  },
  {
    id: 'combat-ready-bestiary-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'Monster bestiary upgraded for combat use',
    summary: 'The Monsters tab now combines the built-in SRD-style monster list with custom creatures, fills missing combat fields where needed, and saves selected creatures as combat encounter seeds.',
    tags: ['Monsters', 'Combat', 'Encounters'],
  },
  {
    id: 'monsters-encounter-builder-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'Monsters can now seed combat encounters',
    summary: 'The Monsters tab has been rebuilt into a creature library with search, filters, quantity selection, encounter naming, and a Save Encounter flow so custom creatures can feed directly into Combat.',
    tags: ['Monsters', 'Combat', 'Encounters'],
  },
  {
    id: 'darker-charcoal-theme-v1',
    date: 'Latest',
    audience: 'Everyone',
    title: 'Darker charcoal background',
    summary: 'The global site background has been darkened from the previous mid-charcoal to a deeper grey, keeping the red and white contrast while making the app feel moodier and less bright.',
    tags: ['Theme', 'Visual Polish'],
  },
  {
    id: 'world-map-upload-fix-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'World map upload fixed and restyled',
    summary: 'The World Map upload flow has been rebuilt with the correct charcoal/red/white theme, a screen-safe upload modal, image preview, and client-side resizing so larger campaign maps are more reliable to save.',
    tags: ['Maps', 'World Atlas', 'Upload'],
  },
  {
    id: 'world-atlas-map-first-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'World section cleaned into World Atlas',
    summary: 'The GM World section is now moving to a map-first structure: world maps hold location pins, location maps hold local points of interest, and the sidebar no longer separates Locations and Maps as competing tabs.',
    tags: ['World', 'Maps', 'Navigation'],
  },
  {
    id: 'sidebar-folder-arrows-v1',
    date: 'Latest',
    audience: 'Everyone',
    title: 'GM sidebar folder arrows and colours cleaned up',
    summary: 'GM sidebar groups now behave more like folders: closed groups point right, open groups point down, and red is reserved for the active/current section instead of open-but-inactive groups.',
    tags: ['GM Dashboard', 'Navigation'],
  },
  {
    id: 'equipped-attuned-reward-handoff-v1',
    date: 'Latest',
    audience: 'GMs and Players',
    title: 'Reward handoff can auto-attune and equip items',
    summary: 'GMs can now choose who receives a party item, auto-attune attunement-required rewards, and grant weapons, armour, shields, or gear as equipped/ready so they land on the character sheet usable straight away.',
    tags: ['Inventory', 'Rewards', 'Character Sheet'],
  },
  {
    id: 'inventory-rewards-rebuild-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'Inventory & Rewards rebuilt',
    summary: 'Party Inventory now uses the real campaign item and currency system. GMs can track shared loot, manage party funds, edit rewards, and grant items directly into linked character sheets.',
    tags: ['Inventory', 'Rewards'],
  },
];

export const LATEST_RELEASE_NOTE_ID = RELEASE_NOTES[0]?.id || 'none';
