export const RELEASE_NOTES = [
  {
    id: 'darker-charcoal-theme-v1',
    date: 'Latest',
    audience: 'Everyone',
    title: 'Darker charcoal background',
    summary: 'The global site background has been darkened from the previous mid-charcoal to a deeper grey, keeping the red and white contrast while making the app feel moodier and less bright.',
    tags: ['Theme', 'Visual Polish'],
  },
  {
    id: 'world-map-upload-fix-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'World map upload fixed and restyled',
    summary: 'The World Map upload flow has been rebuilt with the correct charcoal/red/white theme, a screen-safe upload modal, image preview, and client-side resizing so larger campaign maps are more reliable to save.',
    tags: ['Maps', 'World Atlas', 'Upload'],
  },
  {
    id: 'world-atlas-map-first-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'World section cleaned into World Atlas',
    summary: 'The GM World section is now moving to a map-first structure: world maps hold location pins, location maps hold local points of interest, and the sidebar no longer separates Locations and Maps as competing tabs.',
    tags: ['World', 'Maps', 'Navigation'],
  },
  {
    id: 'sidebar-folder-arrows-v1',
    date: 'Latest',
    audience: 'Everyone',
    title: 'GM sidebar folder arrows and colours cleaned up',
    summary: 'GM sidebar groups now behave more like folders: closed groups point right, open groups point down, and red is reserved for the active/current section instead of open-but-inactive groups.',
    tags: ['GM Dashboard', 'Navigation'],
  },
  {
    id: 'equipped-attuned-reward-handoff-v1',
    date: 'Latest',
    audience: 'GMs and Players',
    title: 'Reward handoff can auto-attune and equip items',
    summary: 'GMs can now choose who receives a party item, auto-attune attunement-required rewards, and grant weapons, armour, shields, or gear as equipped/ready so they land on the character sheet usable straight away.',
    tags: ['Inventory', 'Rewards', 'Character Sheet'],
  },
  {
    id: 'inventory-rewards-rebuild-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'Inventory & Rewards rebuilt',
    summary: 'Party Inventory now uses the real campaign item and currency system. GMs can track shared loot, manage party funds, edit rewards, and grant items directly into linked character sheets.',
    tags: ['Inventory', 'Rewards'],
  },
  {
    id: 'end-session-story-wrap-v2',
    date: 'Latest',
    audience: 'GMs',
    title: 'GM-only End Session story wrap-up',
    summary: 'End Session now includes a GM-only story wrap-up for arc, chapter, and checkpoint tracking. The player-facing end-session display remains dice-only, showing roll stats, awards, and player highlights without story spoilers.',
    tags: ['End Session', 'Story Arcs'],
  },
  {
    id: 'live-story-controls-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'Live Play story controls expanded',
    summary: 'The Live Play story focus strip now supports reaching, skipping, undoing checkpoints, marking the current chapter played, and loading the next chapter without leaving the session screen.',
    tags: ['Live Play', 'Story Arcs'],
  },
  {
    id: 'tonight-checkpoints-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'Tonight’s Session story checkpoint panel',
    summary: 'Tonight’s Session now shows the active arc, current chapter, next checkpoint, chapter progress, and a short checkpoint preview before the GM opens Live Play.',
    tags: ['Tonight’s Session', 'Story Arcs'],
  },
  {
    id: 'tutorials-v1',
    date: 'Latest',
    audience: 'Everyone',
    title: 'First-time page tutorials',
    summary: 'New guided tutorials now appear on supported pages. They explain what each page is for, highlight important areas, and can be replayed using the tutorial button.',
    tags: ['Tutorials', 'New users'],
  },
  {
    id: 'live-story-focus-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'Live Play story checkpoint strip',
    summary: 'Live Play now shows the active story arc, current chapter, next checkpoint, and a Mark Reached button so GMs can track story progress during the session.',
    tags: ['Live Play', 'Story Arcs'],
  },
  {
    id: 'end-session-review-v1',
    date: 'Latest',
    audience: 'GMs and Players',
    title: 'End Session review and animated recap',
    summary: 'GMs now review player roll stats before sending an animated end-session presentation to the extended player display. The recap can show Nat 20s, Nat 1s, awards, player roll leaders, and all-time stats.',
    tags: ['End Session', 'Player Display'],
  },
  {
    id: 'physical-roll-logger-v1',
    date: 'Latest',
    audience: 'Players',
    title: 'Optional physical dice roll logger',
    summary: 'Players who roll real dice can now type d20 results into the character sheet. These logged rolls help build end-session stats and player awards without forcing everyone to use virtual dice.',
    tags: ['Character Sheet', 'Stats'],
  },
  {
    id: 'player-roll-stats-v1',
    date: 'Latest',
    audience: 'Players',
    title: 'Player-focused roll statistics',
    summary: 'Campaign roll stats now focus on player and character rolls first. GM/table rolls are kept separate so the end-session recap feels like a player highlight reel.',
    tags: ['Rolls', 'Stats'],
  },
  {
    id: 'story-checkpoints-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'Story checkpoints inside chapters',
    summary: 'Story Arcs now support checkpoints inside chapters. Checkpoints can be Upcoming, Reached, or Skipped, making it easier to keep going when players move faster than expected.',
    tags: ['Story Arcs', 'Session Prep'],
  },
  {
    id: 'live-play-redesign-v1',
    date: 'Recent',
    audience: 'GMs',
    title: 'Cleaner Live Play Mode',
    summary: 'Live Play has been reorganised into a focused session layout with a tool sidebar, main workspace, quick rail, player display controls, and end-session flow.',
    tags: ['Live Play', 'GM Tools'],
  },
  {
    id: 'gm-dashboard-flow-v1',
    date: 'Recent',
    audience: 'GMs',
    title: 'GM dashboard workflow cleanup',
    summary: 'The GM dashboard now groups tools around the campaign workflow: Command, Prep, World, People, Table, and Library.',
    tags: ['GM Dashboard', 'Navigation'],
  },
  {
    id: 'home-navigation-fix-v1',
    date: 'Recent',
    audience: 'Everyone',
    title: 'More reliable campaign opening from Home',
    summary: 'Campaign and character opening from the Home dashboard now handles more ID formats, reducing the chance of a card failing to open.',
    tags: ['Home', 'Navigation'],
  },
];

export const LATEST_RELEASE_NOTE_ID = RELEASE_NOTES[0]?.id || 'none';
