export const RELEASE_NOTES = [
  {
    id: 'tonight-checkpoints-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'Tonight’s Session story checkpoint panel',
    summary: 'Tonight’s Session now shows the active arc, current chapter, next checkpoint, chapter progress, and a short checkpoint preview before the GM opens Live Play.',
    tags: ['Tonight’s Session', 'Story Arcs'],
  },
  {
    id: 'tutorials-v1',
    date: 'Latest',
    audience: 'Everyone',
    title: 'First-time page tutorials',
    summary: 'New guided tutorials now appear on supported pages. They explain what each page is for, highlight important areas, and can be replayed using the tutorial button.',
    tags: ['Tutorials', 'New users'],
  },
  {
    id: 'live-story-focus-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'Live Play story checkpoint strip',
    summary: 'Live Play now shows the active story arc, current chapter, next checkpoint, and a Mark Reached button so GMs can track story progress during the session.',
    tags: ['Live Play', 'Story Arcs'],
  },
  {
    id: 'end-session-review-v1',
    date: 'Latest',
    audience: 'GMs and Players',
    title: 'End Session review and animated recap',
    summary: 'GMs now review player roll stats before sending an animated end-session presentation to the extended player display. The recap can show Nat 20s, Nat 1s, awards, player roll leaders, and all-time stats.',
    tags: ['End Session', 'Player Display'],
  },
  {
    id: 'physical-roll-logger-v1',
    date: 'Latest',
    audience: 'Players',
    title: 'Optional physical dice roll logger',
    summary: 'Players who roll real dice can now type d20 results into the character sheet. These logged rolls help build end-session stats and player awards without forcing everyone to use virtual dice.',
    tags: ['Character Sheet', 'Stats'],
  },
  {
    id: 'player-roll-stats-v1',
    date: 'Latest',
    audience: 'Players',
    title: 'Player-focused roll statistics',
    summary: 'Campaign roll stats now focus on player and character rolls first. GM/table rolls are kept separate so the end-session recap feels like a player highlight reel.',
    tags: ['Rolls', 'Stats'],
  },
  {
    id: 'story-checkpoints-v1',
    date: 'Latest',
    audience: 'GMs',
    title: 'Story checkpoints inside chapters',
    summary: 'Story Arcs now support checkpoints inside chapters. Checkpoints can be Upcoming, Reached, or Skipped, making it easier to keep going when players move faster than expected.',
    tags: ['Story Arcs', 'Session Prep'],
  },
  {
    id: 'live-play-redesign-v1',
    date: 'Recent',
    audience: 'GMs',
    title: 'Cleaner Live Play Mode',
    summary: 'Live Play has been reorganised into a focused session layout with a tool sidebar, main workspace, quick rail, player display controls, and end-session flow.',
    tags: ['Live Play', 'GM Tools'],
  },
  {
    id: 'gm-dashboard-flow-v1',
    date: 'Recent',
    audience: 'GMs',
    title: 'GM dashboard workflow cleanup',
    summary: 'The GM dashboard now groups tools around the campaign workflow: Command, Prep, World, People, Table, and Library.',
    tags: ['GM Dashboard', 'Navigation'],
  },
  {
    id: 'home-navigation-fix-v1',
    date: 'Recent',
    audience: 'Everyone',
    title: 'More reliable campaign opening from Home',
    summary: 'Campaign and character opening from the Home dashboard now handles more ID formats, reducing the chance of a card failing to open.',
    tags: ['Home', 'Navigation'],
  },
];

export const LATEST_RELEASE_NOTE_ID = RELEASE_NOTES[0]?.id || 'none';
